name: Generate Image

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt para gerar a imagem'
        required: true
        default: 'uma paisagem futurista'
      negative_prompt:
        description: 'Prompt negativo (opcional)'
        required: false
        default: ''
      steps:
        description: 'Número de passos de inferência'
        required: false
        default: '30'
      guidance:
        description: 'Escala de orientação'
        required: false
        default: '7.5'
      width:
        description: 'Largura da imagem'
        required: false
        default: '512'
      height:
        description: 'Altura da imagem'
        required: false
        default: '512'
      seed:
        description: 'Seed para reprodutibilidade (opcional)'
        required: false
        default: ''
      batch:
        description: 'Número de imagens para gerar'
        required: false
        default: '1'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache de dependências
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache do modelo
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-models-v1
        restore-keys: |
          ${{ runner.os }}-huggingface-models-
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Gerar imagem
      run: |
        python action_runner.py \
          --prompt "${{ github.event.inputs.prompt }}" \
          --negative-prompt "${{ github.event.inputs.negative_prompt }}" \
          --steps ${{ github.event.inputs.steps }} \
          --guidance ${{ github.event.inputs.guidance }} \
          --width ${{ github.event.inputs.width }} \
          --height ${{ github.event.inputs.height }} \
          --seed "${{ github.event.inputs.seed }}" \
          --batch ${{ github.event.inputs.batch }}
    
    - name: Upload imagens geradas
      uses: actions/upload-artifact@v4
      with:
        name: generated-images-${{ github.run_number }}
        path: generated_images/*.png
        retention-days: 30
    
    - name: Commit imagens ao repositório
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated_images/*.png
        git diff --staged --quiet || git commit -m "Add generated images from workflow run #${{ github.run_number }}"
        git push
