name: Scheduled Image Generation

on:
  schedule:
    # Executa todos os dias às 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  generate-daily:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache de dependências
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache do modelo
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-models-v1
        restore-keys: |
          ${{ runner.os }}-huggingface-models-
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Gerar prompt aleatório
      id: random-prompt
      run: |
        PROMPTS=(
          "paisagem alienígena com duas luas"
          "cidade cyberpunk à noite com neon"
          "floresta mágica com criaturas bioluminescentes"
          "robô jardineiro cuidando de flores"
          "biblioteca antiga flutuando nas nuvens"
          "submarino explorando cidade subaquática"
          "astronauta plantando árvores em Marte"
          "dragão de cristal em caverna de gelo"
        )
        RANDOM_PROMPT=${PROMPTS[$RANDOM % ${#PROMPTS[@]}]}
        echo "prompt=$RANDOM_PROMPT" >> $GITHUB_OUTPUT
    
    - name: Gerar imagem diária
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python action_runner.py \
          --prompt "${{ steps.random-prompt.outputs.prompt }}" \
          --steps 30 \
          --guidance 7.5
    
    - name: Upload imagem
      uses: actions/upload-artifact@v4
      with:
        name: daily-image-${{ github.run_number }}
        path: generated_images/*.png
        retention-days: 30
